epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - http: 0.0.0.0:40772
  # stream-chunk-size: 4096
  # stream-max-chunks: 30000

channels:
  - name: 'TOKYO MX1'
    type: 'GR'
    channel: '16'

  - name: 'フジテレビ'
    type: 'GR'
    channel: '21'

  - name: 'TBS1'
    type: 'GR'
    channel: '22'

  - name: 'テレビ東京1'
    type: 'GR'
    channel: '23'

  - name: 'テレビ朝日'
    type: 'GR'
    channel: '24'

  - name: '日テレ1'
    type: 'GR'
    channel: '25'

  - name: 'NHKEテレ1東京'
    type: 'GR'
    channel: '26'

  - name: 'NHK総合1・東京'
    type: 'GR'
    channel: '27'

  - name: 'BS朝日1'
    type: 'BS'
    channel: 'BS1_0'
    services: [151]

  - name: 'BS朝日2'
    type: 'BS'
    channel: 'BS1_0'
    services: [152]

  - name: 'BS朝日3'
    type: 'BS'
    channel: 'BS1_0'
    services: [153]

  - name: 'BS-TBS'
    type: 'BS'
    channel: 'BS1_1'
    services: [161]

  - name: 'BS-TBS'
    type: 'BS'
    channel: 'BS1_1'
    services: [162]

  - name: 'BS-TBS'
    type: 'BS'
    channel: 'BS1_1'
    services: [163]

  - name: 'BSテレ東'
    type: 'BS'
    channel: 'BS1_2'
    services: [171]

  - name: 'BSテレ東2'
    type: 'BS'
    channel: 'BS1_2'
    services: [172]

  - name: 'BSテレ東3'
    type: 'BS'
    channel: 'BS1_2'
    services: [173]

  - name: 'NHKBSプレミアム'
    type: 'BS'
    channel: 'BS3_1'
    services: [103]

  - name: 'NHKBSプレミアム'
    type: 'BS'
    channel: 'BS3_1'
    services: [104]

  - name: 'BS11イレブン'
    type: 'BS'
    channel: 'BS9_0'
    services: [211]

  - name: 'BS12トゥエルビ'
    type: 'BS'
    channel: 'BS9_2'
    services: [222]

  - name: 'BSスカパー!'
    type: 'BS'
    channel: 'BS11_0'
    services: [241]

  - name: '放送大学ex'
    type: 'BS'
    channel: 'BS11_1'
    services: [231]

  - name: '放送大学on'
    type: 'BS'
    channel: 'BS11_1'
    services: [232]

  - name: '放送大学ラジオ'
    type: 'BS'
    channel: 'BS11_1'
    services: [531]
    disabled: true

  - name: 'BS日テレ'
    type: 'BS'
    channel: 'BS13_0'
    services: [141]

  - name: 'BS日テレ'
    type: 'BS'
    channel: 'BS13_0'
    services: [142]

  - name: 'BS日テレ'
    type: 'BS'
    channel: 'BS13_0'
    services: [143]

  - name: 'BSフジ・181'
    type: 'BS'
    channel: 'BS13_1'
    services: [181]

  - name: 'BSフジ・182'
    type: 'BS'
    channel: 'BS13_1'
    services: [182]

  - name: 'BSフジ・183'
    type: 'BS'
    channel: 'BS13_1'
    services: [183]

  - name: 'NHKBS1'
    type: 'BS'
    channel: 'BS15_0'
    services: [101]

  - name: 'NHKBS1'
    type: 'BS'
    channel: 'BS15_0'
    services: [102]

  - name: 'グリーンチャンネル'
    type: 'BS'
    channel: 'BS21_2'
    services: [234]

  - name: 'BS松竹東急'
    type: 'BS'
    channel: BS23_3
    services: [260]

tuners:
  - name: PX4-S1
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video0 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-S2
    types: [BS,CS]
    command: >-
      recpt1 --device /dev/px4video1 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T1
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video2 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T2
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video3 {{channel}} {{duration}} -
    disabled: false

filters:
  decode-filter:
    command: arib-b25-stream-test
