services:
  nginx:
    container_name: nginx
    image: nginx:1.26
    ports: [80:80]
    restart: always
    volumes:
      - /Users/${USER}/grafstation/configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/${USER}/grafstation/configs/html:/usr/share/nginx/html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.1.0
    ports: [9090:9090]
    restart: always
    volumes:
      - /Users/${USER}/grafstation/prometheus/:/etc/prometheus/
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.0
    ports: [3000:3000]
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,innius-video-panel,dalvany-image-panel
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    secrets:
      - grafana_admin_password
  aphorism-exporter:
    container_name: aphorism-exporter
    image: legnoh/aphorism-exporter:latest
    ports: [9111:8000]
    restart: always
  asken-exporter:
    container_name: asken-exporter
    image: legnoh/asken-exporter:latest
    ports: [9109:8000]
    restart: always
    environment:
      - ASKEN_USERNAME=${ASKEN_USERNAME}
      - ASKEN_PASSWORD=${ASKEN_PASSWORD}
    shm_size: 2gb
  moneyforward-exporter:
    container_name: moneyforward-exporter
    image: legnoh/moneyforward-exporter:latest
    ports: [9110:8000]
    restart: always
    environment:
      - MONEYFORWARD_EMAIL=${MONEYFORWARD_EMAIL}
      - MONEYFORWARD_PASSWORD=${MONEYFORWARD_PASSWORD}
      - SE_OFFLINE=false
    shm_size: 2gb
  openweather-exporter:
    container_name: openweather-exporter
    image: legnoh/openweather-exporter:icon
    ports: [9103:9091]
    restart: always
    environment:
      - OW_APIKEY=${OPENWEATHER_API_KEY}
      - OW_CITY=${OPENWEATHER_CITY}
      - OW_DEGREES_UNIT=C
      - OW_LANGUAGE=ja
  oura-exporter:
    container_name: oura-exporter
    image: legnoh/oura-exporter:latest
    platform: linux/arm64
    ports: [9112:8000]
    restart: always
    environment:
      - OURA_ACCESS_TOKEN=${OURA_ACCESS_TOKEN}
      - TZ=${OURA_TZ}
  remo-exporter:
    container_name: remo-exporter
    image: kenfdev/remo-exporter:latest
    ports: [9352:9352]
    restart: always
    environment:
      - OAUTH_TOKEN=${NATURE_OAUTH_TOKEN}
  snmp-exporter:
    container_name: snmp-exporter
    image: prom/snmp-exporter:latest
    platform: linux/arm64
    ports: [9106:9116]
    restart: always
    volumes:
      - /Users/${USER}/grafstation/configs/snmp.yml:/etc/snmp_exporter/snmp.yml
  speedtest-exporter:
    container_name: speedtest-exporter
    image: billimek/prometheus-speedtest-exporter:latest
    platform: linux/arm64
    ports: [9469:9469]
    restart: always
    environment:
      - server_ids=${SPEEDTEST_SERVER_IDS}
  withings-exporter:
    container_name: withings-exporter
    image: legnoh/withings-exporter:latest
    platform: linux/arm64
    ports: [9108:8000]
    restart: always
    environment:
      - TZ=${WITHINGS_TZ}
      - WITHINGS_CLIENT_ID=${WITHINGS_CLIENT_ID}
      - WITHINGS_CONSUMER_SECRET=${WITHINGS_CONSUMER_SECRET}
      - WITHINGS_ACCESS_TOKEN=${WITHINGS_ACCESS_TOKEN}
      - WITHINGS_TOKEN_TYPE=Bearer
      - WITHINGS_REFRESH_TOKEN=${WITHINGS_REFRESH_TOKEN}
      - WITHINGS_USERID=${WITHINGS_USERID}
      - WITHINGS_EXPIRES_IN=10800
      - WITHINGS_CREATED=${WITHINGS_CREATED}
    volumes:
      - /Users/${USER}/grafstation/withings:/usr/src/app/config/tmp

secrets:
  grafana_admin_password:
    environment: GRAFANA_ADMIN_PASSWORD
