version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00" # 13:00(UTC+9)
  - package-ecosystem: "terraform"
    directory: "/grafstation/configs/grafana"
    schedule:
      interval: daily
      time: "04:00" # 13:00(UTC+9)
