version: '3.5'
services:
  nginx:
    container_name: nginx
    image: nginx:stable
    ports: [ 80:80 ]
    restart: always
    volumes:
    - /Users/${USER}/life-dashboard/configs/nginx.conf:/etc/nginx/nginx.conf:ro
    - /Users/${USER}/life-dashboard/configs/html:/usr/share/nginx/html:ro
  
  # http://grafstation.local:8888/
  epgstation:
    container_name: epgstation
    image: collelog/epgstation:latest-debian-arm64v8
    ports: ["8888:8888", "8889:8889"]
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /Users/${USER}/life-dashboard/epgstation/config:/opt/epgstation/config
    - /Users/${USER}/life-dashboard/epgstation/data:/opt/epgstation/data
    - /Users/${USER}/life-dashboard/epgstation/drop:/opt/epgstation/drop
    - /Users/${USER}/life-dashboard/epgstation/img:/opt/epgstation/img
    - /Users/${USER}/life-dashboard/epgstation/thumbnail:/opt/epgstation/thumbnail
    - /Users/${USER}/life-dashboard/epgstation/logs:/opt/epgstation/logs
    - /Users/${USER}/life-dashboard/epgstation/recorded:/opt/epgstation/recorded
  
  # https://192-168-XXX-XXX.local.konomi.tv:7777/
  konomitv:
    image: ghcr.io/tsukumijima/konomitv:v0.8.0
    container_name: konomitv
    restart: always
    ports: [ 7777:7000 ]
    volumes:
      - '/Users/${USER}/life-dashboard/konomi/config.yaml:/code/config.yaml'
      - '/Users/${USER}/life-dashboard/konomi/data:/code/server/data'
      - '/Users/${USER}/life-dashboard/konomi/logs:/code/server/logs'
      - '/Users/${USER}/life-dashboard/konomi:/host-rootfs'
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports: [ 9090:9090 ]
    restart: always
    volumes:
    - /Users/${USER}/life-dashboard/prometheus/:/etc/prometheus/
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports: [ 3000:3000 ]
    restart: always
    environment:
    - GF_INSTALL_PLUGINS=grafana-clock-panel,innius-video-panel,aidanmountford-html-panel
  aphorism-exporter:
    container_name: aphorism-exporter
    image: legnoh/aphorism-exporter
    ports: [ "9111:8000" ]
    restart: always
  asken-exporter:
    container_name: asken-exporter
    image: legnoh/asken-exporter
    ports: [ "9109:8000" ]
    restart: always
    environment:
    - ASKEN_USERNAME=${ASKEN_USERNAME}
    - ASKEN_PASSWORD=${ASKEN_PASSWORD}
  moneyforward-exporter:
    container_name: moneyforward-exporter
    image: legnoh/moneyforward-exporter:latest-fixed
    ports: [ "9110:8000" ]
    restart: always
    environment:
    - MONEYFORWARD_EMAIL=${MONEYFORWARD_EMAIL}
    - MONEYFORWARD_PASSWORD=${MONEYFORWARD_PASSWORD}
    - SE_OFFLINE=false
  openweather-exporter:
    container_name: openweather-exporter
    image: legnoh/openweather-exporter
    platform: linux/arm
    ports: [ "9103:9091" ]
    restart: always
    environment:
    - OW_APIKEY=${OPENWEATHER_API_KEY}
    - OW_CITY=${OPENWEATHER_CITY}
  oura-exporter:
    container_name: oura-exporter
    image: legnoh/oura-exporter:latest
    platform: linux/arm64
    ports: [ 9112:8000 ]
    restart: always
    environment:
    - OURA_ACCESS_TOKEN=${OURA_ACCESS_TOKEN}
    - TZ=${OURA_TZ}
  remo-exporter:
    container_name: remo-exporter
    image: kenfdev/remo-exporter:latest
    ports: [ "9352:9352" ]
    restart: always
    environment:
    - OAUTH_TOKEN=${NATURE_OAUTH_TOKEN}
  snmp-exporter:
    container_name: snmp-exporter
    image: prom/snmp-exporter:latest
    platform: linux/arm64
    ports: [ 9106:9116 ]
    restart: always
    volumes:
    - /Users/${USER}/life-dashboard/configs/snmp.yml:/etc/snmp_exporter/snmp.yml
  speedtest-exporter:
    container_name: speedtest-exporter
    image: billimek/prometheus-speedtest-exporter:latest
    platform: linux/arm64
    ports: [ 9469:9469 ]
    restart: always
    environment:
    - server_ids=${SPEEDTEST_SERVER_IDS}
  todoist-exporter:
    container_name: todoist-exporter
    image: legnoh/todoist-exporter:latest
    platform: linux/arm/v7
    ports: [ 9102:8000 ]
    restart: always
    environment:
    - TODOIST_API_KEY=${TODOIST_API_KEY}
  withings-exporter:
    container_name: withings-exporter
    image: legnoh/withings-exporter:latest
    platform: linux/arm64
    ports: [ 9108:8000 ]
    restart: always
    environment:
    - TZ=${WITHINGS_TZ}
    - WITHINGS_CLIENT_ID=${WITHINGS_CLIENT_ID}
    - WITHINGS_CONSUMER_SECRET=${WITHINGS_CONSUMER_SECRET}
    - WITHINGS_ACCESS_TOKEN=${WITHINGS_ACCESS_TOKEN}
    - WITHINGS_TOKEN_TYPE=Bearer
    - WITHINGS_REFRESH_TOKEN=${WITHINGS_REFRESH_TOKEN}
    - WITHINGS_USERID=${WITHINGS_USERID}
    - WITHINGS_EXPIRES_IN=10800
    - WITHINGS_CREATED=${WITHINGS_CREATED}
    volumes:
    - /Users/${USER}/life-dashboard/withings:/usr/src/app/config/tmp
