general:
  kiosk-mode: full
  autofit: true

target:
  login-method: local
  username: admin
  password: admin
  playlist: true
  URL: http://${HOST}:3000/playlists/play/${GRAFANA_PLAYLIST}?autofitpanels
