general:
  kiosk-mode: full
  autofit: true

target:
  login-method: local
  username: grafana-kiosk
  password: grafana-kiosk
  playlist: true
  URL: http://localhost/playlists/play/${GRAFANA_PLAYLIST}?autofitpanels
