name: grafstation
pin: "54739174"
switches:
- meta:
    name: 📈↔︎🎮
  command:
    on:
      path: /usr/bin/open
      args:
      - -a
      - Genki Arcade
    off:
      path: /usr/bin/open
      args:
      - -a
      - Google Chrome
