---

- name: Start Rancher
  block:
    - name: Install/Start Rancher
      ansible.builtin.import_role:
        name: legnoh.dotfiles.install_rancher
      vars:
        install_rancher_memory_in_gb: 8

    - name: Wait dockerd is running
      ansible.builtin.command: "{{ ansible_env.HOME }}/.rd/bin/docker ps"
      retries: 120 # 120 * 5 seconds = 10min (60*60/5)
      delay: 5 # Every 5 seconds
      changed_when: false
