{
 "title": "Life Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "type": "innius-video-panel", "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "帯域通信量",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(ifInOctets[180s])) * 8 / 180",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "回線速度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_downloadedbytes_bytes{}"
    }
   ]
  },
  {
   "title": "部屋の湿度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tado_zone_humidity_percentage{zone_name=\"Air Conditioning\"}"
    }
   ]
  },
  {
   "title": "外の湿度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_humidity{location=\"Kashiwa, JP\"}"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "RasPi帯域",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "step" ] } },
   "targets": [
    {
     "expr": "(node_network_receive_bytes_total{device=\"wlan0\"} + node_network_transmit_bytes_total{device=\"wlan0\"}) * 8 / 60"
    }
   ]
  },
  {
   "title": "瞬間消費電流",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power_consumption_ampare_r{} + power_consumption_ampare_t{}"
    }
   ]
  },
  {
   "title": "外の温度",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(openweather_temperature{location=\"Kashiwa, JP\"} - 32)/1.8"
    }
   ]
  },
  {
   "title": "部屋の温度",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tado_zone_temperature_celsius{zone_name=\"Air Conditioning\"}"
    }
   ]
  },
  {
   "title": "現在の天気",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_currentconditions{location=\"Kashiwa, JP\"}"
    }
   ]
  },
  {
   "title": "自宅タスク残数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "個" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "todoist_filter_task_items{name=\"TODO - 自宅\"}",
     "legendFormat": "自宅"
    },
    {
     "expr": "todoist_filter_task_items{name=\"TODO - 職場\"}",
     "legendFormat": "職場"
    }
   ]
  },
  {
   "title": "歩数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "歩" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "withings_activity_steps" }
   ]
  },
  {
   "title": "バランスシート",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mf_assets_total_jpy - ignoring(type) mf_assets_subtotal_jpy{type=\"年金\"} - (mf_liability_total_jpy - ignoring(type) mf_liability_subtotal_jpy{type=\"奨学金\"})"
    }
   ]
  },
  {
   "title": "VOO S&P500",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mf_assets_mutualfund_gainloss_percent{name=\"SBI-SBI・V・S&P500インデックス・ファンド\"}",
     "legendFormat": "投資信託"
    },
    {
     "expr": "mf_assets_pension_gainloss_percent{name=\"SBI・V・S&P500インデックス・ファンドSBI・V・S&P500インデックス・ファンド\"}",
     "legendFormat": "年金"
    }
   ]
  },
  {
   "title": "睡眠スコア",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "withings_sleep_sleep_score" }
   ]
  },
  {
   "title": "あすけん健康度",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "asken_score{}" }
   ]
  },
  {
   "title": "BMI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "withings_meas_weight / (1.645 ^ 2)"
    }
   ]
  },
  {
   "title": "当月収支",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mf_monthly_balance_jpy" }
   ]
  },
  {
   "title": "借金残高",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-1 * (mf_liability_total_jpy - ignoring(type) mf_liability_subtotal_jpy{type=\"奨学金\"})"
    }
   ]
  },
  {
   "title": "預金残高",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mf_assets_deposit_jpy{account=\"住信SBIネット銀行\", name=\"代表口座-普通\"}"
    }
   ]
  },
  {
   "title": "最高血圧(mmHg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "withings_meas_systolic_blood_pressure{}"
    }
   ]
  },
  {
   "title": "最低血圧(mmHg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "withings_meas_diastolic_blood_pressure{}"
    }
   ]
  },
  {
   "title": "体脂肪率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "withings_meas_fat_ratio" }
   ]
  },
  {
   "title": "カード引落額",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mf_monthly_withdrawal_jpy{name=\"三井住友カード\"}",
     "legendFormat": "三井住友カード"
    },
    {
     "expr": "mf_monthly_withdrawal_jpy{name=\"PayPayカード\"}",
     "legendFormat": "PayPayカード"
    }
   ]
  },
  {
   "title": "残高足りる？",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mf_assets_deposit_jpy{account=\"住信SBIネット銀行\",name=\"代表口座-普通\"} + ignoring(name, account) mf_monthly_withdrawal_jpy{name=\"三井住友カード\"} ",
     "legendFormat": "三井住友カード"
    },
    {
     "expr": "mf_assets_deposit_jpy{account=\"住信SBIネット銀行\",name=\"代表口座-普通\"} + ignoring(name, account) mf_monthly_withdrawal_jpy{name=\"PayPayカード\"}",
     "legendFormat": "PayPayカード"
    }
   ]
  },
  {
   "title": "カード引落日",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mf_monthly_withdrawal_date_info{name=\"三井住友カード\"}",
     "legendFormat": "三井住友カード"
    },
    {
     "expr": "mf_monthly_withdrawal_date_info{name=\"PayPayカード\"}",
     "legendFormat": "PayPayカード"
    }
   ]
  }
 ]
}