---

- name: Start cask apps
  block:
    - name: Install Cask applications
      community.general.homebrew_cask:
        name: flux
        state: upgraded

    - name: Start Flux
      ansible.builtin.command:
        cmd: /usr/bin/open --background -a Flux
      changed_when: false
