---

- name: Start cask apps
  block:
    - name: Install Flux
      community.general.homebrew_cask:
        name: flux
        state: upgraded

    - name: Start Flux
      ansible.builtin.command:
        cmd: /usr/bin/open --background -a Flux
      changed_when: false

    - name: Install/Start Rancher
      ansible.builtin.import_role:
        name: legnoh.dotfiles.install_rancher
      vars:
        install_rancher_memory_in_gb: 5
        install_rancher_number_cpus: 2
        install_rancher_start_in_background: false

    - name: Wait dockerd is running
      ansible.builtin.shell: |
        while true
        do
          if {{ ansible_env.HOME }}/.rd/bin/docker ps > /dev/null; then
            echo "dockerd is running!"
            exit 0
          fi
          echo "dockerd is starting..."
          sleep 5
        done
      changed_when: false
