name: Test Terraform Provider 

on:
  pull_request:
    branches: [main]
    paths:
    - roles/start_grafana_config/files/grafana/**
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./roles/start_grafana_config/files/grafana/
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform command
      uses: hashicorp/setup-terraform@v3

    - name: init
      run: terraform init
