name: Generate SNMP Config
# https://github.com/prometheus/snmp_exporter/tree/main/generator

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/generate-snmp-config.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup GCP Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v0
    - name: Install required packages
      run: sudo apt-get install unzip build-essential libsnmp-dev p7zip-full curl
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Get & Build generator script
      run: |
        git clone https://github.com/prometheus/snmp_exporter.git
        cd snmp_exporter/generator
        go build
        make mibs
    - name: Download YAMAHA Private MIB
      run: |
        curl -Lo yamaha-private-mib.zip http://www.rtpro.yamaha.co.jp/RT/docs/mib/yamaha-private-mib.zip
        unzip yamaha-private-mib.zip
        cp -r yamaha-private-mib/* snmp_exporter/generator/mibs/
    - name: Generate generator.yml
      env:
        SNMP_EXPORTER_MODULE_NAME: ${{ secrets.SNMP_EXPORTER_MODULE_NAME }}
        SNMP_USERNAME: ${{ secrets.SNMP_USERNAME }}
        SNMP_PASSWORD: ${{ secrets.SNMP_PASSWORD }}
        SNMP_PRIV_PASSWORD: ${{ secrets.SNMP_PRIV_PASSWORD }}
        SNMP_CONTEXT_NAME: ${{ secrets.SNMP_CONTEXT_NAME }}
      run: envsubst < ./setup/snmp/tpl/snmp-generator.yml.tpl > ./snmp_exporter/generator/generator.yml
    - name: Execute script
      env:
        MIBDIRS: mibs
      run: |
        cd snmp_exporter/generator
        ./generator generate
    - name: Upload snmp.yml to GCS
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ./snmp_exporter/generator/snmp.yml
        destination: ${{ secrets.GCP_BUCKET_NAME }}/
