name: Generate SNMP Config for YAMAHA NVR510
# https://github.com/prometheus/snmp_exporter/tree/main/generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v2.2.0
      with:
        go-version: 1.17
      id: go
    - name: setup GCP Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v0
    - name: Get & Build generator script
      env: &go_envs
        GO111MODULE: on
        GOPATH: /home/runner/go/
        GENERATOR_PATH: src/github.com/prometheus/snmp_exporter/generator
      run: |
        go get github.com/prometheus/snmp_exporter/generator
        cd ${GOPATH}/${GENERATOR_PATH}
        go build
        make mibs
    - name: Download YAMAHA Private MIB
      run: |
        wget http://www.rtpro.yamaha.co.jp/RT/docs/mib/yamaha-private-mib.zip
        unzip yamaha-private-mib.zip
        cp yamaha-private-mib/* mibs/
    - name: Generate generator.yml
      env:
        SNMP_EXPORTER_MODULE_NAME: ${{ secrets.SNMP_EXPORTER_MODULE_NAME }}
        SNMP_USERNAME: ${{ secrets.SNMP_USERNAME }}
        SNMP_PASSWORD: ${{ secrets.SNMP_PASSWORD }}
        SNMP_PRIV_PASSWORD: ${{ secrets.SNMP_PRIV_PASSWORD }}
        SNMP_CONTEXT_NAME: ${{ secrets.SNMP_CONTEXT_NAME }}
        <<: *go_envs
      run: |
        cd -
        envsubst < ./tpl/snmp-generator.yml.tpl > ${GOPATH}/${GENERATOR_PATH}/generator.yml
        cd -
    - name: Execute script
      env:
        <<: *go_envs
        MIBDIRS: mibs
      run: ./generator generate
    - name: Upload snmp.yml to GCS
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./snmp.yml
        destination: ${{ secrets.BUCKET_NAME }}/
