name: Generate SNMP Config for YAMAHA NVR510
# https://github.com/prometheus/snmp_exporter/tree/main/generator

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/generate-snmp-config.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup GCP Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v0
    - name: Install required packages
      run: sudo apt-get install unzip build-essential libsnmp-dev p7zip-full
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Get & Build generator script
      env:
        GENERATOR_PATH: src/github.com/prometheus/snmp_exporter/generator
      run: |
        go install github.com/prometheus/snmp_exporter/generator@latest
        ls -al /home/runner/
        cd /home/runner/go/${GENERATOR_PATH}
        go build
        make mibs
    - name: Download YAMAHA Private MIB
      run: |
        wget http://www.rtpro.yamaha.co.jp/RT/docs/mib/yamaha-private-mib.zip
        unzip yamaha-private-mib.zip
        cp yamaha-private-mib/* mibs/
    - name: Generate generator.yml
      env:
        SNMP_EXPORTER_MODULE_NAME: ${{ secrets.SNMP_EXPORTER_MODULE_NAME }}
        SNMP_USERNAME: ${{ secrets.SNMP_USERNAME }}
        SNMP_PASSWORD: ${{ secrets.SNMP_PASSWORD }}
        SNMP_PRIV_PASSWORD: ${{ secrets.SNMP_PRIV_PASSWORD }}
        SNMP_CONTEXT_NAME: ${{ secrets.SNMP_CONTEXT_NAME }}
        GENERATOR_PATH: src/github.com/prometheus/snmp_exporter/generator
      run: |
        cd -
        envsubst < ./tpl/snmp-generator.yml.tpl > /home/runner/go/${GENERATOR_PATH}/generator.yml
        cd -
    - name: Execute script
      env:
        GENERATOR_PATH: src/github.com/prometheus/snmp_exporter/generator
        MIBDIRS: mibs
      run: ./generator generate
    - name: Upload snmp.yml to GCS
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./snmp.yml
        destination: ${{ secrets.BUCKET_NAME }}/
