name: Get Latest Metrics Data from GCS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  workflow_run:
    workflows:
    - Reset Crontab setting
    - Reset Grafana KIOSK setting
    types: [ completed ]

jobs:
  setup-raspberry-pi:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: setup GCP Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v1
    - name: Download JSON from GCS
      run: |
        gsutil cp gs://${{ secrets.GCP_BUCKET_NAME }}/*.prom docker/staticfile-exporter/metrics
