name: Get Latest Metrics Data from GCS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  setup-raspberry-pi:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: setup GCP access
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Download JSON from GCS
      run: |
        gsutil cp gs://${{ secrets.GCP_BUCKET_NAME }}/*.prom docker/staticfile-exporter/metrics
