name: Start Grafana Config Daemon

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/grafstation-start-grafana-config.yml'
    - 'grafstation/configs/grafana/**'
  workflow_dispatch:
  workflow_run:
    workflows: [ Start grafstation ]
    types: [ completed ]

jobs:
  setup:
    runs-on: [self-hosted, grafstation]
    if:  ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./grafstation/configs/grafana
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Upgrade .terraform.lock.hcl
      run: |
        terraform init -upgrade
        terraform plan

    - name: copy configs
      run: |
        rm -rf ${HOME}/life-dashboard/configs/grafana
        cp -r ../grafana ${HOME}/life-dashboard/configs/
    
    - name: start gchls daemon
      env:
        GCH_EMAIL: ${{ secrets.GCH_EMAIL }}
        GCH_PASSWORD: ${{ secrets.GCH_PASSWORD }}
        LIST_PATH: "Library/LaunchAgents/io.lkj.life.dashboard.grafstation.grafana.gchls.plist"
      run: |
        export PLIST_PATH="${HOME}/${LIST_PATH}"

        GCH_EMAIL="${GCH_EMAIL}" \
        GCH_PASSWORD="${GCH_PASSWORD}" \
        USER=${USER} \
        envsubst < gchls.plist > ${PLIST_PATH}

        chmod 664 ${PLIST_PATH}
        launchctl unload -w ${PLIST_PATH}
        plutil -lint ${PLIST_PATH}
        launchctl load -w ${PLIST_PATH}

    - name: start terraform daemon
      env:
        NATURE_REMO_DEVICE_NAME: ${{ secrets.NATURE_REMO_DEVICE_NAME }}
        OPENWEATHER_CITY: ${{ secrets.OPENWEATHER_CITY }}
        YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
        LIST_PATH: "Library/LaunchAgents/io.lkj.life.dashboard.grafstation.grafana.apply.plist"
        GRAFSTATION_HOST: "grafstation.local"
      run: |
        export PLIST_PATH="${HOME}/${LIST_PATH}"

        NATURE_REMO_DEVICE_NAME="${NATURE_REMO_DEVICE_NAME}" \
        OPENWEATHER_CITY="${OPENWEATHER_CITY}" \
        YOUTUBE_PLAYLIST_ID="${YOUTUBE_PLAYLIST_ID}" \
        HOST=${GRAFSTATION_HOST} \
        USER=${USER} \
        envsubst < apply.plist > ${PLIST_PATH}

        chmod 664 ${PLIST_PATH}
        launchctl unload -w ${PLIST_PATH}
        plutil -lint ${PLIST_PATH}
        launchctl load -w ${PLIST_PATH}

    - name: Install logrotate config
      run: |
        mkdir -p /opt/homebrew/etc/logrotate.d
        cp -r logrotate.conf /opt/homebrew/etc/logrotate.d/terraform-apply.conf

    - name: Restart logrotate
      run: |
        brew services restart logrotate
