name: Generate SNMP Config
# https://github.com/prometheus/snmp_exporter/tree/main/generator

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/grafstation-generate-snmp-config.yml'
    - 'grafstation/scripts/snmp'
  workflow_run:
    workflows:
    - Install core packages
    types: [ completed ]

jobs:
  build:
    runs-on: [ self-hosted, grafstation ]
    defaults:
      run:
        working-directory: ./grafstation/scripts/snmp
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Generate generator.yml
      env:
        SNMP_USERNAME: ${{ secrets.SNMP_USERNAME }}
        SNMP_PASSWORD: ${{ secrets.SNMP_PASSWORD }}
        SNMP_PRIV_PASSWORD: ${{ secrets.SNMP_PRIV_PASSWORD }}
      run: |
        ./generate.sh
