name: Start Grafana Config Daemon

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/grafstation-start-grafana-config.yml'
    - 'grafstation/configs/grafana/**'
  workflow_dispatch:
  workflow_run:
    workflows: [ Start grafstation ]
    types: [ completed ]

jobs:
  setup:
    runs-on: [self-hosted, grafstation]
    if:  ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./grafstation/configs/grafana
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Upgrade .terraform.lock.hcl
      env:
        LIST_PATH: "Library/LaunchAgents/io.lkj.life.dashboard.grafstation.grafana.apply.plist"
        GRAFANA_AUTH: "admin:${{ secrets.GRAFANA_ADMIN_PASSWORD }}"
      run: |
        export PLIST_PATH="${HOME}/${LIST_PATH}"
        if [[ -f "${PLIST_PATH}" ]]; then
          chmod 664 ${PLIST_PATH}
          launchctl unload -w ${PLIST_PATH}
        fi
        
        terraform init -upgrade
        terraform plan

        if [[ -f "${PLIST_PATH}" ]]; then
          plutil -lint ${PLIST_PATH}
          launchctl load -w ${PLIST_PATH}
        fi

    - name: copy configs
      run: |
        rm -rf ${HOME}/life-dashboard/configs/grafana
        cp -r ../grafana ${HOME}/life-dashboard/configs/

    - name: start terraform daemon
      env:
        ABEMA_JWT_TOKEN: ${{ secrets.ABEMA_JWT_TOKEN }}
        GRAFANA_AUTH: admin:${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        GREENCH_EMAIL: ${{ secrets.GREENCH_EMAIL }}
        GREENCH_PASSWORD: ${{ secrets.GREENCH_PASSWORD }}
        NATURE_REMO_DEVICE_NAME: ${{ secrets.NATURE_REMO_DEVICE_NAME }}
        OPENWEATHER_CITY: ${{ secrets.OPENWEATHER_CITY }}
        YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
        LIST_PATH: "Library/LaunchAgents/io.lkj.life.dashboard.grafstation.grafana.apply.plist"
        GRAFSTATION_HOST: "grafstation.local"
      run: |
        export PLIST_PATH="${HOME}/${LIST_PATH}"

        ABEMA_JWT_TOKEN="${ABEMA_JWT_TOKEN}" \
        GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD}" \
        GREENCH_EMAIL="${GREENCH_EMAIL}" \
        GREENCH_PASSWORD="${GREENCH_PASSWORD}" \
        NATURE_REMO_DEVICE_NAME="${NATURE_REMO_DEVICE_NAME}" \
        OPENWEATHER_CITY="${OPENWEATHER_CITY}" \
        YOUTUBE_PLAYLIST_ID="${YOUTUBE_PLAYLIST_ID}" \
        HOST="${GRAFSTATION_HOST}" \
        USER="${USER}" \
        envsubst < apply.plist > ${PLIST_PATH}

        chmod 664 ${PLIST_PATH}
        launchctl unload -w ${PLIST_PATH}
        plutil -lint ${PLIST_PATH}
        launchctl load -w ${PLIST_PATH}

    - name: Install logrotate config
      run: |
        mkdir -p /opt/homebrew/etc/logrotate.d
        cp -r logrotate.conf /opt/homebrew/etc/logrotate.d/terraform-apply.conf

    - name: Restart logrotate
      run: |
        brew services restart logrotate
