name: Start GCHLS Daemon

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/grafstation-start-gchls.yml'
    - 'grafstation/configs/gchls/**'
  workflow_dispatch:
  workflow_run:
    workflows: [ Start grafstation ]
    types: [ completed ]

jobs:
  setup:
    runs-on: [self-hosted, grafstation]
    if:  ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./grafstation/configs/gchls
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: copy configs
      run: |
        rm -rf ${HOME}/life-dashboard/configs/gchls
        cp -r ../gchls ${HOME}/life-dashboard/configs/
    
    - name: start gchls daemon
      env:
        GCH_EMAIL: ${{ secrets.GCH_EMAIL }}
        GCH_PASSWORD: ${{ secrets.GCH_PASSWORD }}
        LIST_PATH: "Library/LaunchAgents/io.lkj.life.dashboard.grafstation.grafana.gchls.plist"
      run: |
        export PLIST_PATH="${HOME}/${LIST_PATH}"

        GCH_EMAIL="${GCH_EMAIL}" \
        GCH_PASSWORD="${GCH_PASSWORD}" \
        USER=${USER} \
        envsubst < gchls.plist > ${PLIST_PATH}

        chmod 664 ${PLIST_PATH}
        launchctl unload -w ${PLIST_PATH}
        plutil -lint ${PLIST_PATH}
        launchctl load -w ${PLIST_PATH}

    - name: Install logrotate config
      run: |
        mkdir -p /opt/homebrew/etc/logrotate.d
        cp -r logrotate.conf /opt/homebrew/etc/logrotate.d/gchls.conf

    - name: Restart logrotate
      run: |
        brew services restart logrotate
