name: Start Grafana KIOSK setting

on:
  push:
    branches:
    - main
    paths:
    - 'grafstation/configs/grafana-kiosk-config.yml'
  workflow_dispatch:
  workflow_run:
    workflows: [ Start grafstation ]
    types: [ completed ]
jobs:
  setup:
    runs-on: [self-hosted, grafstation]
    if: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./grafstation
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create .grafana-kiosk.config.yml
      run: |
        GRAFANA_PLAYLIST=$(curl -s -u admin:admin "http://localhost:3000/api/playlists" | jq -r ".[0].uid") \
        envsubst < ./configs/grafana-kiosk-config.yml \
        > ${HOME}/.grafana-kiosk-config.yml

    - name: Setup grafana-kiosk
      run: |
        brew services stop grafana-kiosk
        brew services start grafana-kiosk
