name: Start Grafana Config Daemon

on:
  push:
    branches:
    - main
    paths:
    - 'grafstation/configs/grafana/**'
  workflow_dispatch:
  workflow_run:
    workflows: [ Start grafstation ]
    types: [ completed ]

jobs:
  setup:
    runs-on: [self-hosted, grafstation]
    if: ${{ github.event.push }} || ${{ github.event.workflow_dispatch }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./grafstation/configs/grafana
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Upgrade .terraform.lock.hcl
      run: |
        terraform init -upgrade
        terraform plan

    - name: copy configs
      run: |
        cp -r ../grafana ${HOME}/life-dashboard/configs/

    - name: start terraform daemon
      env:
        OPENWEATHER_CITY: ${{ secrets.OPENWEATHER_CITY }}
        YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
        LIST_PATH: "Library/LaunchAgents/io.lkj.life.dashboard.grafstation.grafana.apply.plist"
        GRAFSTATION_HOST: "grafstation.local"
      run: |
        export PLIST_PATH="${HOME}/${LIST_PATH}"

        OPENWEATHER_CITY="${OPENWEATHER_CITY}" \
        YOUTUBE_PLAYLIST_ID="${YOUTUBE_PLAYLIST_ID}" \
        HOST=${GRAFSTATION_HOST} \
        USER=${USER} \
        envsubst < apply.plist > ${PLIST_PATH}

        chmod 664 ${PLIST_PATH}
        launchctl unload -w ${PLIST_PATH}
        plutil -lint ${PLIST_PATH}
        launchctl load -w ${PLIST_PATH}

    - name: Install logrotate config
      run: |
        cp -r logrotate.conf /opt/homebrew/etc/logrotate.d/terraform-apply.conf

    - name: Restart logrotate
      run: |
        brew services restart logrotate
