name: Install core packages

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/grafstation-install-core.yml'
    - 'roles/install-brew-packages/**'
  workflow_dispatch:

jobs:
  install:
    runs-on: [self-hosted, grafstation]
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Execute
      run: ansible-playbook site.yml -i inventory/localhost.yml -t "brew" -v
      env:
        GRAFSTATION_SUDO_PASS: ${{ secrets.GRAFSTATION_SUDO_PASS }}
