name: Install core packages

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/grafstation-install-core.yml'
    - 'grafstation/configs/Brewfile'
  workflow_dispatch:

jobs:
  install:
    runs-on: [self-hosted, grafstation]
    defaults:
      run:
        working-directory: ./grafstation
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Install Core Packages
      run: |
        curl -Lo ~/.Brewfile https://github.com/legnoh/life-dashboard/raw/main/grafstation/configs/Brewfile
        brew bundle --global
    
    - name: Update existed Packages
      run: |
        brew update
        brew upgrade
    
    - name: Open docker
      run: |
        open --background -a Docker
