name: Start mirakc

on:
  push:
    branches:
    - main
    paths:
    - 'mirakc/**'
  workflow_dispatch:
    inputs:
      rm_state:
        description: 'inject docker compose down'
        type: boolean
        default: false

jobs:
  setup:
    runs-on: [self-hosted, mirakc]
    defaults:
      run:
        working-directory: ./mirakc
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Copy configs
      run: |
        mkdir -p ${HOME}/life-dashboard/mirakc/configs
        cp -r * ${HOME}/life-dashboard/mirakc/configs/
    
    - name: start docker images
      env:
        RECREATE_CONTAINER: ${{ inputs.rm_state }}
      run: |
        ./compose.sh
