name: Start mirasmart

on:
  push:
    branches:
    - main
    paths:
    - 'mirasmart/**'
  workflow_dispatch:
    inputs:
      rm_state:
        description: 'inject docker compose down'
        type: boolean
        default: false

jobs:
  setup:
    runs-on: [self-hosted, mirasmart]
    defaults:
      run:
        working-directory: ./mirasmart
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: start docker images
      env:
        RECREATE_CONTAINER: ${{ inputs.rm_state }}
        SMARTMETER_ID: ${{ secrets.SMARTMETER_ID }}
        SMARTMETER_PASSWORD: ${{ secrets.SMARTMETER_PASSWORD }}
      run: |
        ./start.sh
