name: Reset docker-compose setting

on:
  push:
    branches:
    - main
    paths:
    - 'docker/**'
  workflow_dispatch:
  workflow_run:
    workflows: [ Generate SNMP Config ]
    types: [ completed ]

jobs:
  setup-raspberry-pi:
    runs-on: self-hosted
    strategy:
      matrix:
        python: [3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup GCP Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v0
    - name: Download JSON from GCS
      run: |
        gsutil cp gs://${{ secrets.GCP_BUCKET_NAME }}/*.prom docker/staticfile-exporter/metrics
    - name: Download snmp.yml from GCS
      run: |
        gsutil cp gs://${{ secrets.GCP_BUCKET_NAME }}/snmp.yml docker/snmp-exporter
    - name: start docker images
      env:
        OPENWEATHER_CITY: ${{ secrets.OPENWEATHER_CITY }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        OPENWEATHER_LISTEN_ADDRESS: ${{ secrets.OPENWEATHER_LISTEN_ADDRESS }}
        SNMP_EXPORTER_MODULE_NAME: ${{ secrets.SNMP_EXPORTER_MODULE_NAME }}
        SNMP_TARGET_IP: ${{ secrets.SNMP_TARGET_IP }}
        TADOAC_USERNAME: ${{ secrets.TADOAC_USERNAME }}
        TADOAC_PASSWORD: ${{ secrets.TADOAC_PASSWORD }}
        TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
        SMARTMETER_ID: ${{ secrets.SMARTMETER_ID }}
        SMARTMETER_PASSWORD: ${{ secrets.SMARTMETER_PASSWORD }}
        GRAFANA_REMOTE_WRITE_USERNAME: ${{ secrets.GRAFANA_REMOTE_WRITE_USERNAME }}
        GRAFANA_REMOTE_WRITE_API_KEY: ${{ secrets.GRAFANA_REMOTE_WRITE_API_KEY }}
        WITHINGS_CLIENT_ID: ${{ secrets.WITHINGS_CLIENT_ID }}
        WITHINGS_CONSUMER_SECRET: ${{ secrets.WITHINGS_CONSUMER_SECRET }}
        WITHINGS_ACCESS_TOKEN: ${{ secrets.WITHINGS_ACCESS_TOKEN }}
        WITHINGS_REFRESH_TOKEN: ${{ secrets.WITHINGS_REFRESH_TOKEN }}
        WITHINGS_USERID: ${{ secrets.WITHINGS_USERID }}
        WITHINGS_CREATED: ${{ secrets.WITHINGS_CREATED }}
      run: |
        ./docker/start.sh
    # - name: Archive production artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: artifact
    #     path: |
    #       docker
