name: Restart mirasmart

on:
  push:
    branches:
    - main
    paths:
    - 'mirasmart/**'
  workflow_dispatch:
    inputs:
      rm_state:
        description: 'inject docker compose rm'
        type: boolean
        default: false

jobs:
  restart:
    runs-on: [self-hosted, mirasmart]
    defaults:
      run:
        working-directory: ./mirasmart
    steps:
    - uses: actions/checkout@v3
    - name: start docker images
      env:
        DOCKER_COMPOSE_RM: ${{ inputs.rm_state }}
        SMARTMETER_ID: ${{ secrets.SMARTMETER_ID }}
        SMARTMETER_PASSWORD: ${{ secrets.SMARTMETER_PASSWORD }}
      run: |
        ./mirasmart/start.sh
