name: Setup RaspberryPi

on:
  workflow_dispatch:

jobs:
  setup-raspberry-pi:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: set crontab
      run: |
        sudo cp -r ./crontab/bin/* /usr/local/bin/
        sudo cp -r ./crontab/settings/* /etc/cron.d/
        echo "success copy crontab scripts"
    - name: install docker
      run: |
        ./docker/install.sh
    - name: setup grafana-kiosk
      env:
          GRAFANA_KIOSK_URL: ${{ secrets.GRAFANA_KIOSK_URL }}
          GRAFANA_KIOSK_USERNAME: ${{ secrets.GRAFANA_KIOSK_USERNAME }}
          GRAFANA_KIOSK_PASSWORD: ${{ secrets.GRAFANA_KIOSK_PASSWORD }}
      run: |
        ./grafana-kiosk/install.sh
    - name: setup GCP Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v1
    - name: Download JSON from GCS
      run: |
        gsutil cp gs://${{ secrets.GCP_BUCKET_NAME }}/*.prom docker/staticfile-exporter/metrics
