name: Upload Numerics JSON to Netlify

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: test docker
      run: sudo docker images
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pipenv
    #     pipenv install
    # - name: setup GCP access
    #   uses: google-github-actions/setup-gcloud@master
    #   with:
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - name: Download JSON from GCS
    #   run: gsutil cp gs://${{ secrets.BUCKET_NAME }}/*.prom container/public
