name: terraform ci

on:
  pull_request:
    branches:
    - main
    paths:
    - grafstation/configs/grafana/
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./grafstation/configs/grafana/
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform command
      uses: hashicorp/setup-terraform@v3
    
    - name: init
      run: terraform init
